" load system defaults
if filereadable("/etc/vimrc")
  source /etc/vimrc
endif
if filereadable("/etc/vim/vimrc")
  source /etc/vim/vimrc
endif

" add our vimruntimepath
let &runtimepath = &runtimepath . ',' . expand("$DOTFILESPATH") . '/vim'

" Tabs
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

" Search
set smartcase
set ignorecase

" Appearance
set laststatus=2
colorscheme darcula
syntax on
